#!/usr/bin/env bash
#Displaying a fun story for better understanding of the /etc/passwd file format

USERNAME=/etc/passwd | cut -d: -f 1;
GROUP_ID=/etc/passwd | cut -d: -f 4;
HOME_DIRECTORY=/etc/passwd | cut -d: -f 6;
COMMANDSHELL=/etc/passwd | cut -d: -f 7;
USER_ID=/etc/passwd | cut -d: -f 3;
PASSWORD=/etc/passwd | cut -d: -f 2;

while read -r /etc/passwd
 
  do
      echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMANDSHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: USER ID INFO"
  
  done
