#!/usr/bin/env bash
#Will display Best School 10 times, but in the 9th iteration it displays Best School and then hi

i=0

while [ $i -le 9 ]
 do
    echo "Best School"

    if [[ $i -gt 8 ]]
      then
	      echo -e "Hi\nBest School"
	  (( i++))
    else
	((i++))
    fi
 done 
