#!/usr/bin/env bash
#Will display Best School 10 times, but in the 9th iteration it displays Best School and then hi

i=0

while [ $i -le 8 ]
 do
    if [[ $i -lt 8 ]]
      then
	      echo "Best School"
	  (( i++))
    else
	echo -e "Hi\nBest School"
	    ((i++))
    fi
 done 
