#!/usr/bin/env bash
#Script displays "bad luck" in the 4th loop // "good luck" in the 8th loop // "Best School" for all others

i=0

while [ $i -le 9 ]
   do
      if [[ $i = 3 ]]
	 then
	      echo "bad luck"
	   (( i++ ))
    elif [[ $i = 7 ]]
         then 
	      echo "good luck" 
  	   (( i++ ))
    else
	echo "Best School"
	   (( i++ ))
    fi
done
        
