#!/usr/bin/env bash
#Will display num 1-20 // 4 display 'bad luck from China // 9 display 'bad luck from Japan' // 17 display bad luck from Italy

i=1

while [ $i -le 20 ]
do 
   if [[ $i = 4 || $i = 9 || $i = 17 ]]
   then
   case $i in
	4)	echo "bad luck from China"
		;;
	9)	echo "bad luck from Japan"
		;;
	17)	echo "bad luck from Italy"
		;;
	
	esac
else
	echo $i
   fi
	(( i++ ))
done

