#!/usr/bin/env bash
#Will display hours from 0 to 12 // display minutes from 1 to 59 // for 13 hours and 59 minutes

i=0
j=0

while [ $i -le 12 ]
  do
    echo "Hour: " $i
    j=0
 until [ $j -gt 59 ]
   do
    echo $j
        (( j++ ))
    done
        (( i++ ))
  done
