#!/usr/bin/env bash
#Script displays content of current directory in a list format, only showing the name after the first dash
#not showing hidden files

for i in *
     do 
	echo "$i" | cut -d- f 2   
     done
