#!/usr/bin/env bash
#Script will display if file exists or not //

if [[ -e "school" ]]
then
   echo "school file exists"
 if [[ -s "school" ]]
 then
   echo "school file is empty"
 elif [[ ! -s "school" ]] 
 then
   echo "school file is not empty"
 elif [[ -f "school" ]]
 then
   echo "school is a regular file"
 fi
# loop file does not exist
else
   echo "school file does not exist"

fi
